// Initialize and add the map
var geocoder;
var map;
function addMarker(name,address) {
    geocoder.geocode( { 'address': address}, function(results, status) {
        if (status == 'OK') {
          var marker = new google.maps.Marker({
              title: name,
              map: map,
              position: results[0].geometry.location
          });
        } else {
          alert('Geocode was not successful for the following reason: ' + status);
        }
      });
}
function initMap() {
    geocoder = new google.maps.Geocoder();
    const houston = { lat: 29.820, lng: -95.467 };
    map = new google.maps.Map(document.getElementById("map"), {
        zoom: 8,
        center: houston,
      });

    // The location of Houston
    addMarker("Harris County Courthouse","301 Fannin St. Houston, TX 77002");
    addMarker(" ABOVE AND BEYOND FELLOWSHIP(BOTH) "," 20498 RHODES ROAD SPRING TX 77388 ");
    addMarker(" ACRES HOMES MULTI SERVICE CENTER(BOTH) "," 6719 WEST MONTGOMERY ROAD HOUSTON TX 77091 ");
    addMarker(" ALIEF ISD ADMINISTRATION BUILDING(BOTH) "," 4250 COOK ROAD HOUSTON TX 77072 ");
    addMarker(" ALIEF ISD CENTER FOR TALENT DEVELOPMENT(BOTH) "," 14411 WESTHEIMER ROAD HOUSTON TX 77082 ");
    addMarker(" ALVIN D BAGGETT COMMUNITY CENTER(BOTH) "," 1302 KEENE STREET GALENA PARK TX 77547 ");
    addMarker(" BAKERRIPLEY EAST ALDINE CAMPUS(BOTH) "," 3000 ALDINE MAIL ROUTE ROAD HOUSTON TX 77039 ");
    addMarker(" BAYLAND PARK COMMUNITY CENTER(BOTH) "," 6400 BISSONNET STREET HOUSTON TX 77074 ");
    addMarker(" BAYTOWN COMMUNITY CENTER(BOTH) "," 2407 MARKET STREET BAYTOWN TX 77520 - 6204 ");
    addMarker(" BIG STONE LODGE(BOTH) "," 709 RILEY FUZZEL ROAD SPRING TX 77373 ");
    addMarker(" C. E. KING 9TH GRADE CENTER(BOTH) "," 8530 C E KING PARKWAY HOUSTON TX 77044 ");
    addMarker(" CHINESE CIVIC CENTER(BOTH) "," 5905 SOVEREIGN DRIVE HOUSTON TX 77036 ");
    addMarker(" CITY JERSEY VILLAGE MUNICIPAL GOVERNMENT CENTER(BOTH) "," 16327 LAKEVIEW DRIVE HOUSTON TX 77040 - 2029 ");
    addMarker(" CITY OF SOUTH HOUSTON MUNICIPAL COURT(BOTH) "," 1019 DALLAS STREET SOUTH HOUSTON TX 77587 ");
    addMarker(" CLEVELAND RIPLEY NEIGHBORHOOD CENTER(BOTH) "," 720 FAIRMONT PARKWAY PASADENA TX 77504 ");
    addMarker(" CROSBY BRANCH LIBRARY(BOTH) "," 135 HARE ROAD CROSBY TX 77532 ");
    addMarker(" DAMASCUS MISSIONARY BAPTIST CHURCH(BOTH) "," 3122 CENTER STREET HOUSTON TX 77077 ");
    addMarker(" DELMAR TUSA SPORTS COMPLEX(BOTH) "," 2020 MANGUM ROAD HOUSTON TX 77092 ");
    addMarker(" DENVER HARBOR PARK COMMUNITY CENTER(BOTH) "," 6402 MARKET STREET HOUSTON TX 77020 - 6840 ");
    addMarker(" EAST HARRIS COUNTY ACTIVITY CENTER(BOTH) "," 7340 SPENCER HIGHWAY PASADENA TX 77505 ");
    addMarker(" EL FRANCO LEE COMMUNITY CENTER(BOTH) "," 9500 HALL ROAD HOUSTON TX 77089 - 1042 ");
    addMarker(" EVELYN KENNEDY CIVIC CENTER(BOTH) "," 618 SAN JACINTO STREET LA PORTE TX 77571 ");
    addMarker(" FAIRFIELD INN AND SUITES(BOTH) "," 10825 N GESSNER RD HOUSTON TX 77064 ");
    addMarker(" FALLBROOK CHURCH(BOTH) "," 12512 WALTERS ROAD HOUSTON TX 77014 ");
    addMarker(" FIRST CONGREGATIONAL CHURCH(BOTH) "," 10840 BEINHORN RD HOUSTON TX 77024 ");
    addMarker(" FOREST BEND HOMEOWNERS ASSOCIATION INC(BOTH) "," 4300 LAURA LEIGH DRIVE FRIENDSWOOD TX 77546 - 4168 ");
    addMarker(" FOUNTAIN OF LIFE CENTER(BOTH) "," 14083 SOUTH MAIN STREET HOUSTON TX 77035 ");
    addMarker(" FREEMAN BRANCH LIBRARY(BOTH) "," 16616 DIANA LANE HOUSTON TX 77062 ");
    addMarker(" GIRL SCOUTS OF SAN JACINTO COUNCIL(BOTH) "," 3000 SOUTHWEST FREEWAY HOUSTON TX 77098 ");
    addMarker(" GREEN HOUSE INTERNATIONAL CHURCH(BOTH) "," 200 WEST GREENS ROAD HOUSTON TX 77067 ");
    addMarker(" HAMPTON INN AND SUITES HOUSTON KATY(BOTH) "," 22055 KATY FREEWAY KATY TX 77450 ");
    addMarker(" HARDY STREET SENIOR CITIZENS CENTER(BOTH) "," 11901 WEST HARDY ROAD HOUSTON TX 77076 - 1220 ");
    addMarker(" HARRIS COUNTY SCARSDALE ANNEX(BOTH) "," 10851 SCARSDALE BOULEVARD HOUSTON TX 77089 ");
    addMarker(" HCC ALIEF CENTER(BOTH) "," 13803 BISSONNET HOUSTON TX 77083 ");
    addMarker(" HCC NORTH FOREST CAMPUS(BOTH) "," 6010 LITTLE YORK ROAD HOUSTON TX 77016 ");
    addMarker(" HCC SOUTHEAST COLLEGE BUILDING D(BOTH) "," 6815 RUSTIC STREET HOUSTON TX 77087 ");
    addMarker(" HCC WEST LOOP SOUTH(BOTH) "," 5601 WEST LOOP SOUTH HOUSTON TX 77081 ");
    addMarker(" HCPL BARBARA BUSH BRANCH(BOTH) "," 6817 CYPRESSWOOD DRIVE SPRING TX 77379 - 7705 ");
    addMarker(" HCPL MAUD SMITH MARKS BRANCH LIBRARY(BOTH) "," 1815 WESTGREEN BOULEVARD KATY TX 77450 - 5370 ");
    addMarker(" HIRAM CLARKE MULTI SERVICE CENTER(BOTH) "," 3810 WEST FUQUA STREET HOUSTON TX 77045 - 6402 ");
    addMarker(" HOCKLEY COMMUNITY CENTER(BOTH) "," 28515 OLD WASHINGTON ROAD HOCKLEY TX 77447 - 7842 ");
    addMarker(" HOLIDAY INN EXPRESS &amp; SUITES ATASCOCITA(BOTH) "," 5619 FARM TO MARKET 1960 ROAD EAST HUMBLE TX 77346 ");
    addMarker(" HOLIDAY INN EXPRESS &amp; SUITES HOUSTON MEMORIAL - CITY CENTRE(BOTH) "," 10500 KATY FREEWAY HOUSTON TX 77043 ");      
    addMarker(" HOSANNA LUTHERAN CHURCH(BOTH) "," 16526 ELLA BLVD HOUSTON TX 77090 ");
    addMarker(" HOUSTON COMMUNITY COLLEGE NORTHLINE(BOTH) "," 8001 FULTON STREET HOUSTON TX 77022 ");
    addMarker(" HUMBLE CIVIC CENTER(BOTH) "," 8233 WILL CLAYTON PARKWAY HUMBLE TX 77338 ");
    addMarker(" J D WALKER COMMUNITY CENTER(BOTH) "," 7613 WADE ROAD BAYTOWN TX 77521 - 8338 ");
    addMarker(" JOHN KNOX PRESBYTERIAN CHURCH(BOTH) "," 2525 GESSNER ROAD HOUSTON TX 77080 - 3800 ");
    addMarker(" JOHN P MCGOVERN TEXAS MEDICAL CENTER COMMONS(BOTH) "," 6550 BERTNER AVENUE HOUSTON TX 77030 ");
    addMarker(" JOHN PAUL LANDING ENVIRONMENTAL EDUCATION CENTER(BOTH) "," 9950 KATY HOCKLEY ROAD CYPRESS TX 77433 ");
    addMarker(" JOHN PHELPS COURTHOUSE(BOTH) "," 101 SOUTH RICHEY STREET PASADENA TX 77506 ");
    addMarker(" JUERGENS HALL COMMUNITY CENTER(BOTH) "," 26026 HEMPSTEAD HIGHWAY CYPRESS TX 77429 - 7321 ");
    addMarker(" KASHMERE MULTISERVICE CENTER(BOTH) "," 4802 LOCKWOOD DRIVE HOUSTON TX 77026 - 2941 ");
    addMarker(" KATY BRANCH HARRIS COUNTY PUBLIC LIBRARY(BOTH) "," 5414 FRANZ ROAD KATY TX 77493 - 1717 ");
    addMarker(" KINGWOOD COMMUNITY CENTER(BOTH) "," 4102 RUSTIC WOODS DRIVE KINGWOOD TX 77345 - 1350 ");
    addMarker(" KLEIN MULTIPURPOSE CENTER(BOTH) "," 7500 FM 2920 SPRING TX 77379 - 2204 ");
    addMarker(" LA QUINTA INN &amp; SUITES BY WYNDHAM HOUSTON GALLERIA(BOTH) "," 1625 WEST LOOP SOUTH HOUSTON TX 77027 ");
    addMarker(" LONE STAR COLLEGE CREEKSIDE(BOTH) "," 8747 WEST NEW HARMONY TRAIL TOMBALL TX 77375 ");
    addMarker(" LONE STAR COLLEGE NORTH HARRIS(BOTH) "," 2005 W W THORNE BOULEVARD HOUSTON TX 77073 ");
    addMarker(" LONE STAR COLLEGE VICTORY CENTER(BOTH) "," 4141 VICTORY DRIVE HOUSTON TX 77088 ");
    addMarker(" MARTIN FLUKINGER COMMUNITY CENTER(BOTH) "," 16003 LORENZO STREET CHANNELVIEW TX 77530 ");
    addMarker(" MASJID ALSALAM(BOTH) "," 16700 OLD LOUETTA ROAD SPRING TX 77379 ");
    addMarker(" METROPOLITAN MULTISERVICE CENTER(BOTH) "," 1475 WEST GRAY STREET HOUSTON TX 77019 - 4926 ");
    addMarker(" MILTON LUSK ACTIVITY CENTER(BOTH) "," 1022 MERCURY DRIVE HOUSTON TX 77029 ");
    addMarker(" MISSION BEND ISLAMIC CENTER(BOTH) "," 6233 TRES LAGUNAS HOUSTON TX 77083 ");
    addMarker(" MOODY PARK COMMUNITY CENTER(BOTH) "," 3725 FULTON STREET HOUSTON TX 77009 ");
    addMarker(" NEIGHBORHOOD CENTERS INC RIPLEY HOUSE CAMPUS(BOTH) "," 4410 NAVIGATION BOULEVARD HOUSTON TX 77011 - 1036 ");
    addMarker(" NORTH CHANNEL BRANCH LIBRARY(BOTH) "," 15741 WALLISVILLE ROAD HOUSTON TX 77049 - 4607 ");
    addMarker(" NORTH EAST COMMUNITY CENTER(BOTH) "," 10918 BENTLY STREET HOUSTON TX 77093 ");
    addMarker(" NORTHEAST MULTI SERVICE CENTER(BOTH) "," 9720 SPAULDING STREET HOUSTON TX 77016 ");
    addMarker(" NOTTINGHAM PARK BUILDING(BOTH) "," 926 COUNTRY PLACE DRIVE HOUSTON TX 77079 ");
    addMarker(" NRG ARENA(BOTH) "," 1 NRG PKWY HOUSTON TX 77054 ");
    addMarker(" PRAIRIE VIEW A&amp;M UNIVERSITY NORTHWEST(BOTH) "," 9449 GRANT ROAD HOUSTON TX 77070 ");
    addMarker(" RAINDROP TURKISH HOUSE(BOTH) "," 9301 WEST BELLFORT BOULEVARD HOUSTON TX 77031 ");
    addMarker(" RICHARD AND MEG WEEKLEY COMMUNITY CENTER(BOTH) "," 8440 GREENHOUSE ROAD CYPRESS TX 77433 - 5135 ");
    addMarker(" RILEY CHAMBERS COMMUNITY CENTER(BOTH) "," 808 1/2 MAGNOLIA AVENUE CROSBY TX 77532 ");
    addMarker(" SAINT JOHN LUTHERAN CHURCH(BOTH) "," 15235 SPRING CYPRESS ROAD CYPRESS TX 77429 ");
    addMarker(" SAINT PHILIP NERI CATHOLIC CHURCH(BOTH) "," 10960 MARTIN LUTHER KING BOULEVARD HOUSTON TX 77048 - 1896 ");
    addMarker(" SAMUEL MATTHEWS PARK COMMUNITY CENTER(BOTH) "," 1728 HUFSMITH ROAD TOMBALL TX 77375 - 4918 ");
    addMarker(" SAN JACINTO COLLEGE GENERATION PARK(BOTH) "," 13455 LOCKWOOD ROAD HOUSTON TX 77029 ");
    addMarker(" SAN JACINTO COMMUNITY CENTER(BOTH) "," 604 HIGHLAND WOODS DRIVE HIGHLANDS TX 77562 - 4546 ");
    addMarker(" SHERATON HOUSTON BROOKHOLLOW HOTEL(BOTH) "," 3000 NORTH LOOP WEST FREEWAY HOUSTON TX 77092 - 8810 ");
    addMarker(" SHRINE OF THE BLACK MADONNA CULTURAL AND EVENT CENTER(BOTH) "," 5309 MARTIN LUTHER KING BLVD HOUSTON TX 77021 ");      
    addMarker(" SPJST LODGE NUM 88(BOTH) "," 1435 BEALL STREET HOUSTON TX 77008 - 3441 ");
    addMarker(" STEVE RADACK COMMUNITY CENTER(BOTH) "," 18650 CLAY ROAD HOUSTON TX 77084 ");
    addMarker(" SUNNYSIDE MULTI SERVICE CENTER(BOTH) "," 9314 CULLEN BOULEVARD HOUSTON TX 77051 ");
    addMarker(" TEXAS SOUTHERN UNIVERSITY(BOTH) "," 3100 CLEBURNE STREET HOUSTON TX 77004 ");
    addMarker(" THE COLLECTIVE-THE POWER CENTER(BOTH) "," 12401 SOUTH POST OAK ROAD HOUSTON TX 77045 - 2020 ");
    addMarker(" THE GRAND TUSCANY HOTEL(BOTH) "," 12801 NORTHWEST FREEWAY HOUSTON TX 77040 ");
    addMarker(" TOM BASS PARK COMMUNITY CENTER SECTION THREE(BOTH) "," 15108 CULLEN BOULEVARD HOUSTON TX 77047 - 6714 ");
    addMarker(" TOMBALL PUBLIC WORKS BUILDING(BOTH) "," 501 B JAMES STREET TOMBALL TX 77375 ");
    addMarker(" TRACY GEE COMMUNITY CENTER(BOTH) "," 3599 WESTCENTER DRIVE HOUSTON TX 77042 ");
    addMarker(" TRINI MENDENHALL COMMUNITY CENTER(BOTH) "," 1414 WIRT ROAD HOUSTON TX 77055 - 4917 ");
    addMarker(" UNIVERSITY OF HOUSTON CLEAR LAKE(BOTH) "," 2700 BAY AREA BLVD HOUSTON TX 77058 ");
    addMarker(" UNIVERSITY OF HOUSTON STUDENT CENTER(BOTH) "," 4455 UNIVERSITY DRIVE HOUSTON TX 77004 ");
    addMarker(" UNIVERSITY OF HOUSTON-DOWNTOWN(BOTH) "," 201 GIRARD STREET HOUSTON TX 77002 ");
    addMarker(" VERA BRUMMET MAY COMMUNITY CENTER(BOTH) "," 2100 WOLF ROAD HUFFMAN TX 77336 ");
    addMarker(" VICTORY HOUSTON(BOTH) "," 809 WEST ROAD HOUSTON TX 77038 ");
    addMarker(" WEBSTER CIVIC CENTER(BOTH) "," 311 PENNSYLVANIA AVENUE WEBSTER TX 77598 ");
    addMarker(" WHEELER AVENUE BAPTIST CHURCH(BOTH) "," 3826 WHEELER AVENUE BUILDING D HOUSTON TX 77004 ");
  }
  
  window.initMap = initMap;